version: '3'
services:
    db:
      image: 'postgres:latest'
      environment:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: crudapirest
      volumes:
          - ./pgdata:/var/lib/postgresql/data
      ports:
          - "5432:5432"
